# Mobile Verification Toolkit (MVT)
# Copyright (c) 2021-2023 The MVT Authors.
# Use of this software is governed by the MVT License 1.1 that can be found at
#   https://license.mvt.re/1.1/

"""Lightweight case summary / report generator for MVT iOS output directories."""

import json
import logging
import os
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from mvt.common.version import MVT_VERSION

log = logging.getLogger("mvt")

_SKIP_JSON = frozenset(
    {"alerts.json", "correlation.json", "case_summary.json", "info.json"}
)
_LEVEL_ORDER = ("CRITICAL", "HIGH", "MEDIUM", "LOW", "INFORMATIONAL")


def _verdict_from_alerts(alerts: List[Dict[str, Any]]) -> str:
    if not alerts:
        return "CLEAN"
    levels_seen = {a.get("level", "") for a in alerts}
    for level in _LEVEL_ORDER:
        if level in levels_seen:
            return level
    return "UNKNOWN"


def _normalize_alert_counts(alerts: List[Dict[str, Any]]) -> Dict[str, int]:
    counts: Dict[str, int] = {lvl: 0 for lvl in _LEVEL_ORDER}
    counts["total"] = len(alerts)
    for alert in alerts:
        level = alert.get("level", "")
        if level in counts:
            counts[level] += 1
    return counts


def _count_jsonl_lines(path: str) -> int:
    count = 0
    try:
        with open(path, encoding="utf-8") as fh:
            for line in fh:
                if line.strip():
                    count += 1
    except OSError:
        pass
    return count


def _count_json_array(path: str) -> int:
    try:
        with open(path, encoding="utf-8") as fh:
            data = json.load(fh)
        if isinstance(data, list):
            return len(data)
    except (OSError, json.JSONDecodeError):
        pass
    return 0


def _render_markdown(s: Dict[str, Any]) -> List[str]:
    verdict = s.get("verdict", "UNKNOWN")
    ac = s.get("alert_counts", {})
    lines = [
        "# MVT Case Summary",
        "",
        "| Field | Value |",
        "|---|---|",
        f"| MVT Version | {s.get('mvt_version', '')} |",
        f"| Generated | {s.get('generated_at', '')} |",
        f"| Case ID | {s.get('case_id', '') or '—'} |",
        f"| Analyst | {s.get('analyst', '') or '—'} |",
        f"| Input Directory | `{s.get('input_dir', '')}` |",
        f"| **Verdict** | **{verdict}** |",
        "",
        "## Alert Summary",
        "",
        "| Level | Count |",
        "|---|---|",
    ]
    for level in _LEVEL_ORDER:
        lines.append(f"| {level} | {ac.get(level, 0)} |")
    lines.append(f"| **Total** | **{ac.get('total', 0)}** |")

    ioc_matches = s.get("ioc_matches", [])
    if ioc_matches:
        lines += [
            "",
            "## IOC Matches",
            "",
            "| Value | Type | Name | Module | Level |",
            "|---|---|---|---|---|",
        ]
        for m in ioc_matches:
            lines.append(
                f"| {m.get('value', '')} | {m.get('type', '')} |"
                f" {m.get('name', '')} | {m.get('module', '')} | {m.get('alert_level', '')} |"
            )

    correlation = s.get("correlation_findings", [])
    if correlation:
        lines += [
            "",
            "## Correlation Findings",
            "",
            f"Found {len(correlation)} correlation finding(s).",
        ]

    artifact_counts = s.get("module_artifact_counts", {})
    if artifact_counts:
        lines += [
            "",
            "## Artifact Counts by Module",
            "",
            "| Module | Records |",
            "|---|---|",
        ]
        for slug, count in sorted(artifact_counts.items()):
            lines.append(f"| {slug} | {count} |")

    lines += [
        "",
        "---",
        "",
        "_Generated by [MVT](https://mvt.re)._",
    ]
    return lines


class CaseReport:
    """Reads an MVT output directory and produces a structured case summary."""

    def __init__(
        self,
        input_dir: str,
        case_id: str = "",
        analyst: str = "",
    ) -> None:
        self.input_dir = os.path.abspath(input_dir)
        self.case_id = case_id
        self.analyst = analyst

    def _read_json_file(self, filename: str) -> Any:
        path = os.path.join(self.input_dir, filename)
        if not os.path.isfile(path):
            return None
        try:
            with open(path, encoding="utf-8") as fh:
                return json.load(fh)
        except (OSError, json.JSONDecodeError) as exc:
            log.warning("Could not read %s: %s", path, exc)
            return None

    def _scan_module_artifacts(self) -> Dict[str, int]:
        counts: Dict[str, int] = {}
        try:
            entries = os.listdir(self.input_dir)
        except OSError:
            return counts
        for entry in entries:
            if not entry.endswith(".json") or entry in _SKIP_JSON:
                continue
            slug = entry[: -len(".json")]
            counts[slug] = _count_json_array(os.path.join(self.input_dir, entry))
        return counts

    def _scan_timeline_records(self) -> Dict[str, int]:
        counts: Dict[str, int] = {}
        try:
            entries = os.listdir(self.input_dir)
        except OSError:
            return counts
        for entry in entries:
            if not entry.endswith("_normalized.jsonl"):
                continue
            slug = entry[: -len("_normalized.jsonl")]
            counts[slug] = _count_jsonl_lines(os.path.join(self.input_dir, entry))
        return counts

    def _extract_ioc_matches(
        self, alerts: List[Dict[str, Any]]
    ) -> List[Dict[str, Any]]:
        seen: set = set()
        matches: List[Dict[str, Any]] = []
        for alert in alerts:
            ioc = alert.get("matched_indicator")
            if not ioc:
                continue
            ioc_value = (
                ioc.get("value", "") if isinstance(ioc, dict) else str(ioc)
            )
            if not ioc_value or ioc_value in seen:
                continue
            seen.add(ioc_value)
            matches.append(
                {
                    "value": ioc_value,
                    "type": ioc.get("type", "") if isinstance(ioc, dict) else "",
                    "name": ioc.get("name", "") if isinstance(ioc, dict) else "",
                    "module": alert.get("module", ""),
                    "alert_level": alert.get("level", ""),
                }
            )
        return matches

    def build(self) -> Dict[str, Any]:
        """Build and return the case summary dict without writing any files."""
        alerts: List[Dict[str, Any]] = self._read_json_file("alerts.json") or []
        correlation: List[Dict[str, Any]] = (
            self._read_json_file("correlation.json") or []
        )
        artifact_counts = self._scan_module_artifacts()
        timeline_counts = self._scan_timeline_records()
        ioc_matches = self._extract_ioc_matches(alerts)
        verdict = _verdict_from_alerts(alerts)

        return {
            "mvt_version": MVT_VERSION,
            "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
            "case_id": self.case_id,
            "analyst": self.analyst,
            "input_dir": self.input_dir,
            "verdict": verdict,
            "alert_counts": _normalize_alert_counts(alerts),
            "alerts": alerts,
            "correlation_findings": correlation,
            "ioc_matches": ioc_matches,
            "module_artifact_counts": artifact_counts,
            "timeline_record_counts": timeline_counts,
        }

    def save_json(
        self,
        output_path: str,
        summary: Optional[Dict[str, Any]] = None,
    ) -> None:
        if summary is None:
            summary = self.build()
        with open(output_path, "w", encoding="utf-8") as fh:
            json.dump(summary, fh, indent=2, default=str)
        log.info("Case summary written to %s", output_path)

    def save_markdown(
        self,
        output_path: str,
        summary: Optional[Dict[str, Any]] = None,
    ) -> None:
        if summary is None:
            summary = self.build()
        with open(output_path, "w", encoding="utf-8") as fh:
            fh.write("\n".join(_render_markdown(summary)) + "\n")
        log.info("Case summary (markdown) written to %s", output_path)
